---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: travel-control
  namespace: {{ .Values.username }}-travel-control-new
  annotations:
    argocd.argoproj.io/sync-wave: "2"      
spec:
  to:
    kind: Service
    name: control-vm
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
