---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-selective-principals
  namespace: {{ .Values.username }}-travel-control-new
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/istio-gateway/sa/gateway-shared-istio"]
