---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-nothing
  namespace: {{ .Values.username }}-travel-control-new
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec: {}
