---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: control-vm
  namespace: {{ .Values.username }}-travel-control-new
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: fedora-control
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
        sidecar.istio.io/inject: 'true'
        istio.io/reroute-virtual-interfaces: "k6t-eth0"
      labels:
        kubevirt.io/domain: control-vm
        kubevirt.io/size: small
        app: control-vm
        version: v1
        sidecar.istio.io/inject: 'true'
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 1Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: fedora-control
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: redhat
              chpasswd: { expire: False }
              ssh_pwauth: true
              runcmd:
              - loginctl enable-linger fedora
              - su - fedora -c 'XDG_RUNTIME_DIR=/run/user/$(id -u) DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus" systemctl --user daemon-reload'
              - su - fedora -c 'XDG_RUNTIME_DIR=/run/user/$(id -u) DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus" systemctl --user start control.service'
              write_files:
              - content: |
                  [Unit]
                  Description=Fedora Control Container
                  [Container]
                  Label=app=control-container
                  ContainerName=control-container
                  Image=quay.io/kiali/demo_travels_control:v1
                  Environment=PORTAL_SERVICES='voyages.fr;http://voyages.{{ .Values.username }}-travel-portal.svc.cluster.local:8000,viaggi.it;http://viaggi.{{ .Values.username }}-travel-portal.svc.cluster.local:8000,travels.uk;http://travels.{{ .Values.username }}-travel-portal.svc.cluster.local:8000'
                  PodmanArgs=-p 8080:8080
                  [Install]
                  WantedBy=multi-user.target default.target
                  [Service]
                  Restart=always
                path: /etc/containers/systemd/users/control.container
                permissions: '0777'
                owner: root:root
          name: cloudinitdisk
