apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.component_id }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    gitlab.com/project-slug: ${{ values.owner }}/${{ values.component_id }}
spec:
  type: service
  lifecycle: development
  owner: user:${{ values.owner }}
